### ISSUE TITLE
Loading Channels is erroring out

### ISSUE THREAD

**Issue by Protektor-Desura** [fHDHR/fHDHR_STIRR#7]
It won't load channels or the guide. I am getting this error.

```
Loading fHDHR v0.4.6-beta
Loading fHDHR_web v0.4.0-beta
Loading Origin Service: fHDHR_Locast v0.5.0-beta
Loading Configuration File: /app/config/config.ini
Warning: Do not run fHDHR with root privileges.
Traceback (most recent call last):
  File "/app/main.py", line 20, in <module>
    sys.exit(run.main(SCRIPT_DIR, fHDHR_web, origin, alternative_epg))
  File "/app/fHDHR/cli/run.py", line 113, in main
    return start(args, script_dir, fHDHR_web, origin, alternative_epg)
  File "/app/fHDHR/cli/run.py", line 101, in start
    return run(settings, logger, db, script_dir, fHDHR_web, origin, alternative_epg)
  File "/app/fHDHR/cli/run.py", line 76, in run
    fhdhr.api.client.get("/api/startup_tasks")
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/test.py", line 1006, in get
    return self.open(*args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/flask/testing.py", line 222, in open
    return Client.open(
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/test.py", line 970, in open
    response = self.run_wsgi_app(environ.copy(), buffered=buffered)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/test.py", line 861, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/test.py", line 1096, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/fHDHR_web/api/startup_tasks.py", line 15, in __call__
    return self.get(*args)
  File "/app/fHDHR_web/api/startup_tasks.py", line 28, in get
    self.fhdhr.api.client.get(self.channel_update_url)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/test.py", line 1006, in get
    return self.open(*args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/flask/testing.py", line 222, in open
    return Client.open(
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/test.py", line 970, in open
    response = self.run_wsgi_app(environ.copy(), buffered=buffered)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/test.py", line 861, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/test.py", line 1096, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/fHDHR_web/api/channels.py", line 15, in __call__
    return self.get(*args)
  File "/app/fHDHR_web/api/channels.py", line 131, in get
    self.fhdhr.device.channels.get_channels(forceupdate=True)
  File "/app/fHDHR/device/channels/__init__.py", line 80, in get_channels
    channel_dict_list = self.origin.get_channels()
  File "/app/fHDHR/originwrapper/__init__.py", line 37, in get_channels
    return self.channels.get_channels()
  File "/app/origin/origin_channels.py", line 49, in get_channels
    stirr_chan_item = chan_item_urlopn.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by deathbybandaid** [comment]
Works find here

**Comment by deathbybandaid** [comment]
![Screenshot_20201218-171844_Firefox](https://user-images.githubusercontent.com/18010545/102666502-20029d80-4155-11eb-9e77-33806773e460.jpg)

**Comment by Protektor-Desura** [comment]
Are you using Python 3.8?

**Comment by deathbybandaid** [comment]
Yes

**Comment by deathbybandaid** [comment]
![Screenshot_20201218-172051_Firefox](https://user-images.githubusercontent.com/18010545/102666622-6c4ddd80-4155-11eb-97f7-15c6105e0597.jpg)

**Comment by Protektor-Desura** [comment]
Hmm same exact info in mine.

How does this ini look?

```
[main]
uuid = nmnmtomq
cache_dir = 
servicename = STIRR
reponame = fHDHR_STIRR

[fhdhr]
address = 0.0.0.0
discovery_address = 0.0.0.0
port = 5004
stream_type = direct
tuner_count = 4
friendlyname = fHDHR-STIRR
reporting_firmware_name = fHDHR_STIRR
reporting_manufacturer = BoronDust
reporting_model = fHDHR
reporting_firmware_ver = 20201001
reporting_tuner_type = Antenna
device_auth = fHDHR

[epg]
images = pass
method = origin
update_frequency = 43200

[ffmpeg]
path = ffmpeg
bytes_per_read = 1152000

[vlc]
path = cvlc
bytes_per_read = 1152000

[direct_stream]
chunksize = 1048576

[logging]
level = INFO

[database]
type = sqlite
driver = None

[stirr]
force_best = False

[web_ui]
advanced = True
```

**Comment by Protektor-Desura** [comment]
Did you get a chance to look at this?

**Comment by deathbybandaid** [comment]
I did not. I'm on vacation, and not at a coding capable computer. Please feel free to poke at the api and see if you can find an issue on your network

**Comment by Protektor-Desura** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gevent/pywsgi.py", line 970, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python3.8/dist-packages/gevent/pywsgi.py", line 917, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/fHDHR_web/api/channels.py", line 15, in __call__
    return self.get(*args)
  File "/app/fHDHR_web/api/channels.py", line 131, in get
    self.fhdhr.device.channels.get_channels(forceupdate=True)
  File "/app/fHDHR/device/channels/__init__.py", line 80, in get_channels
    channel_dict_list = self.origin.get_channels()
  File "/app/fHDHR/originwrapper/__init__.py", line 37, in get_channels
    return self.channels.get_channels()
  File "/app/origin/origin_channels.py", line 49, in get_channels
    stirr_chan_item = chan_item_urlopn.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-12-19T02:01:58Z {'REMOTE_ADDR': '127.0.0.1', 'REMOTE_PORT': '47856', 'HTTP_HOST': '0.0.0.0:5004', (hidden keys: 22)} failed with JSONDecodeError

**Comment by deathbybandaid** [comment]
Discovery address can't be 0.0.0.0

**Comment by Protektor-Desura** [comment]
Change it to the actual IP of the server (192.168.50.10) and still throwing an error and not loading channels.

**Comment by Protektor-Desura** [comment]
Traceback (most recent call last):
  File "/app/main.py", line 20, in <module>
    sys.exit(run.main(SCRIPT_DIR, fHDHR_web, origin, alternative_epg))
  File "/app/fHDHR/cli/run.py", line 113, in main
    return start(args, script_dir, fHDHR_web, origin, alternative_epg)
  File "/app/fHDHR/cli/run.py", line 101, in start
    return run(settings, logger, db, script_dir, fHDHR_web, origin, alternative_epg)
  File "/app/fHDHR/cli/run.py", line 76, in run
    fhdhr.api.client.get("/api/startup_tasks")
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/test.py", line 1006, in get
    return self.open(*args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/flask/testing.py", line 222, in open
    return Client.open(
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/test.py", line 970, in open
    response = self.run_wsgi_app(environ.copy(), buffered=buffered)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/test.py", line 861, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/test.py", line 1096, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/fHDHR_web/api/startup_tasks.py", line 15, in __call__
    return self.get(*args)
  File "/app/fHDHR_web/api/startup_tasks.py", line 28, in get
    self.fhdhr.api.client.get(self.channel_update_url)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/test.py", line 1006, in get
    return self.open(*args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/flask/testing.py", line 222, in open
    return Client.open(
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/test.py", line 970, in open
    response = self.run_wsgi_app(environ.copy(), buffered=buffered)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/test.py", line 861, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/test.py", line 1096, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/fHDHR_web/api/channels.py", line 15, in __call__
    return self.get(*args)
  File "/app/fHDHR_web/api/channels.py", line 131, in get
    self.fhdhr.device.channels.get_channels(forceupdate=True)
  File "/app/fHDHR/device/channels/__init__.py", line 80, in get_channels
    channel_dict_list = self.origin.get_channels()
  File "/app/fHDHR/originwrapper/__init__.py", line 37, in get_channels
    return self.channels.get_channels()
  File "/app/origin/origin_channels.py", line 49, in get_channels
    stirr_chan_item = chan_item_urlopn.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
fHDHR - INFO - HTTP Server Online.

**Comment by deathbybandaid** [comment]
As stated above, I can't get to it right away.

Please show a modicum of patience.

**Comment by deathbybandaid** [comment]
I'm also not sure why your environment is using simplejson

**Comment by deathbybandaid** [comment]
You test the newest push yet?

**Comment by deathbybandaid** [comment]
how 'bout now?

**Comment by Protektor-Desura** [comment]
Well I am able to get the channels list but it looks like the guide info is empty. It does download something but there are no descriptions and just says "unknown" for everything in the guide.

**Comment by Protektor-Desura** [comment]
![Screenshot (108)](https://user-images.githubusercontent.com/1195496/102712307-c2ba3980-4285-11eb-9dd1-bbac8a5028e3.png)

**Comment by deathbybandaid** [comment]
Stirr doesn't provide much for epg, you can try adjusting your update frequency in the config file
